module Predicateable
  def self.included: (Module base) -> void

  module ClassMethods : Module
    def predicate: (
      Symbol | String name,
      Array[Symbol | String] values,
      ?prefix: bool,
      ?strict: bool
    ) -> Array[Symbol | String]
  end
end
